spring:
  datasource:
    url: jdbc:sqlserver://192.168.14.113:1433;databaseName=SASDEV;encrypt=true;trustServerCertificate=true;
    username: adm01
    password: DEVOPDB!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
server:
  port: 8081

logging:
  level:
    org.springframework: DEBUG